name: "Terraform"

on:
  push:
    branches:
      - main
      - github-ci
  pull_request:

jobs:
  terraform:
    name: "Unit Tests"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 0.14.0
          terraform_wrapper: false

      - name: Terraform Format
        id: fmt
        run: terraform fmt -check
        continue-on-error: true

      - name: Terraform Validate
        id: validate
        # if: github.event_name == 'pull_request'
        run: terraform init && terraform validate -no-color
        env:
          AWS_DEFAULT_REGION: "us-east-1"
